<?php

namespace AppBundle\Repository;

/**
 * GroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBygroupeId($groupe)
    {
        $query = $this->getEntityManager()
                      ->createQuery('
                            SELECT u
                            FROM AppBundle:User u
                            JOIN u.groupe g 
                            WHERE g.id = :groupe
                      ');
        $query->setParameter('groupe', $groupe);
        return $query->getResult();
    }
}
